name: Package Binary
on:
  workflow_dispatch:

jobs:
  build-windows:
    env:
      dist-path: dist/OpenSeeFace
    runs-on: windows-latest
    steps:
      - name: Pull OpenSeeFace
        uses: actions/checkout@v3

      - name: Create binary
        shell: cmd
        run: |
          choco install vcredist140
          xcopy c:\Windows\System32\msvcp140.dll .
          xcopy c:\Windows\System32\vcomp140.dll .
          xcopy c:\Windows\System32\concrt140.dll .
          xcopy c:\Windows\System32\vccorlib140.dll .
          make_exe.bat

      - name: Move files for uploading
        shell: bash
        run: |
          mv dist/facetracker ${{ env.dist-path }}
          cp -r models ${{ env.dist-path }}

      - name: Upload artifact
        uses: ./.github/actions/upload-dated-artifact
        with:
          name: windows
          path: dist
